### ISSUE TITLE
do you know what is biggest data for credit scoring available in internet to try ?

### ISSUE THREAD

**Issue by Sandy4321** [adimajo/scoringTools#3]
I see your code one of best world wide
An Overview on the Landscape of R  Packages for Credit Scoring july 2020
https://arxiv.org/pdf/2006.11835.pdf

but only how it would work with big data
lets say 30 GB data?
do you know what is biggest data for credit scoring available in internet to try ?

**Comment by adimajo** [comment]
Thanks.
I don't know of any that big.
Classicaly, financial institutions don't release such big datasets.
Even internally, since there are relatively few features, datasets are not that big.
However, recently, there has been some interest in the field for transactional data.
See e.g. this master thesis: https://repository.tudelft.nl/islandora/object/uuid:6ed89f2f-2c5f-4b85-859b-47a244da609b/datastream/OBJ/download
But even in that case, I don't know of any public dataset.
